services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - nginx
    volumes:
      - beta_files:/var/www/app/
  nginx:
    container_name: webserver
    image: nginx-alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
    volumes:
      - web_files:/var/www/app/
version: '3.7'
